---
title: "Inflation or Illusion? Examining Bias in the CPI"
author: "Uma Nair"
date: "2024-10-25"
output: pdf_document
---


## Introduction

The Consumer Price Index (CPI) is often praised  as a vital tool for understanding inflation, monetary policy, and the overall economic health of a country, but it might not tell the whole story. But what if the very measure used to gauge economic well-being was intentionally flawed? The CPI is a measure of the average change over time in the prices paid by urban consumers for a market basket of consumer goods and services (US Bureau of Labor Statistics). However, despite the CPI’s immense influence on the economy, many citizens have little to no knowledge about the CPI and the harm that a biased CPI value can do. There has been a longstanding debate regarding bias in the CPI estimates since the 70s, causing some economists to focus their research on why this bias occurs and how to effectively minimize it. This paper explores the literature review, research methodology, results, and ethical dilemmas regarding the dissertation "Bias in the Consumer Price Index: What is the Evidence" from the Journal of Economic Perspectives by Brent R. Moulton. The study focuses mainly on the mathematical, economic, and political reasons for the inherent bias in the CPI through statistical analysis, field work, and observation, but it also underscores the social impact of an inflated or understated CPI, such as how it affects consumer purchasing power and those in poverty. 


The differences between estimates seem to be largely determined by the willingness of experts to extrapolate from these case studies to estimates for broader categories of goods. Many different economists can interpret the same data in different ways, causing dispute over estimates. Additionally, economists tend to “guesstimate” CPI indices for convenience and fail to capture many confounding variables that affect the accuracy of the CPI, such as substitution bias, sampling bias, and quality-change bias. Substitution bias refers to the CPI’s inability to account for consumer’s switching from one product to another due to price changes, sampling error can be caused by taking an unrepresentative sample of consumers. If data is taken from a region with more upper-middle class/wealthy families, the basket of goods and services will look very different in comparison to an area with food deserts and subsidized housing. Quality-change bias can occur if the CPI does not consider the upgrade in quality of existing goods. The available research results may reflect a kind of selection effect, where researchers have tended to study the goods for which there is a strong presumption of possible bias, like computers, prescription drugs, etc. Bias in the CPI impinges on most of the measurements economists make of economic growth and well-being. The CPI is often used directly to deflate nominal measures to ''real" units, such as real wages. The CPI component indexes are also used by the Bureau of Economic Analysis to deflate personal consumption expenditures in constructing the national income accounts, so biases in the CPI could lead to biased measures of real growth and productivity. Over a period of 25 years, a bias of that magnitude would cause the growth of quantities deflated by the CPI, such as real wages, to be understated by 19 percent. A similar paper titled "Sources of Bias and Solutions to Bias in the Consumer Price Index" by Jerry Hausman from the Journal of Economic Perspectives affirms these conclusions, stating “The U.S. government should devote significant resources to the measurement of the Consumer Price Index because economic knowledge of consumer welfare depends, in large part, on drawing an accurate separation between real and nominal changes”, as nominal changes do not account for factors such as inflation and seasonality, whereas real changes do. (Hausman, 2003). Additionally, the CPI is directly impacted by income and purchasing power of citizens, which is how researchers quantified and examined the effects of bias in the CPI.


## Research Methodology

In the paper, the results of another analysis paper regarding bias in the CPI was produced. The paper that contained the analysis, titled Using Survey Data to Assess Bias in the Consumer Price Index by Alan B. Krueger and Aaron Siskind. The purpose of the paper was to see if the “comparisons of self-reports with actual changes in families’ financial status indicate that the CPI may measure such changes reliably”(Krueger et. al). The study uses qualitative data, and provides an estimate of the extent of bias in the CPI by comparing the net proportion of families that report an improvement in their financial situation with changes in real median income. Specifically, he bases his analysis on time-series data collected by the University of Michigan’s Institute for Social Research (ISR) in its Survey of Consumers. Among other things, this survey, which is used to measure consumer confidence, asks respondents whether their families’ financial situation improved or worsened in the past year. The author estimates the implied bias in the CPI by determining the growth rate of real median income that is associated with an equal number of families reporting an improvement, compared with a decline, in their financial situation. “[Their] point estimate suggests that the CPI is biased upwards by 1.5 percentage points”(Krueger et. al). Each month, the ISR’s Survey of Consumers contains the following question: “We are interested in how people are getting along financially these days. Would you say that you (and your family living there) are better off or worse off financially than you were a year ago?” with the possible answers of “Better”, “Same” , “Worse” , or “Don’t Know”. The analysis presented subtracts the percentage of families that report a worsening in their financial situation from the percentage that report an improvement and creates an annual series by averaging each twelve calendar months of data. The resulting values  are referred to as the “net percentage of families whose financial situation improved”. The authors regresses the net percentage of families whose financial situation improved on the percent change in median real household income, using the CPI-U (CPI for urban consumers) to deflate income. The regression model is stated as Y = a + bX. “Y is the percentage of families that report an improvement in their financial situation, minus the percentage that report a worsening, and X is the percent change in median household income from the CPS, deflated by the CPI-U. The ratio –a/b is an estimate of the percent change in measured real income that is associated with an equal number of families reporting an improvement and a worsening in their financial well-being, estimate of the bias in the CPI”(Krueger et. al). Deflating by the CPI-U-X1 probably provides a better guide for the bias in the present-day CPI, however. Consequently, the first of the two columns headed “CPI-U-X1” in table 1 presents a re-estimate of the same model as in the previous column, but now using the CPI-U-X1 to deflate median income growth. These results yield a smaller, but still substantial, 1.2- percentage-point-per-year bias in the CPI. The researchers continued to make multiple regression lines to see how the percentage points of bias vary between different samples of individuals and their subsequent answers to the question. According to Krueger and Siskind, “) If the regression Y = a ' + b ' Z, is estimated, and if income is properly deflated, one would expect to find that a = 0 and b = 1. A joint test of these coefficient restrictions provides a more robust test of bias in the CPI than does Nordhaus’ regression of Y on median real-income growth (X), because the restrictions should hold even if the shape of the income distribution changes over time”.

Additionally, the paper used government data that can easily be found online through agencies such as the US Bureau of Labor Statistics and FRED, or the Federal Reserve Economic Data. From these sources,  historical price data can be collected for a variety of consumer goods and services. A bootstrapping test in Python can be performed where researchers find and bootstrap a large sample of estimated CPI and see if they converge to the expected value (population mean CPI). Then, a histogram of the distribution could be created, along with  a confidence interval along with p-value calculation (with an alpha of .05) from there. To add onto the data analysis, I would also like  to create another plot (using the seaborn or matplotlib modules in Python) to create a comprehensive graph of the changes in consumer prices and goods over the last decade, along with their “guesstimate” prices that experts have deemed to be the correct price of the goods in services in the basket. I will also create dataframes in Python to demonstrate and analyze substitution bias. 

## Ethical Considerations and the Moral Dilemma

Why is it an issue that the CPI is understated or not accurate? An under or overstatement of the CPI can have detrimental effects on the economy as well as the individual consumer, completely altering the balance of the economy and consumer spending habits. A biased CPI can lead to misguided assumptions and estimates regarding inflation rates causing policy makers and economists to make inaccurate predictions, affecting decisions regarding monetary policy. Central banks may keep interest rates lower for longer than needed if they believe that the inflation rate is lower than it actually is, leading to economic imbalances. Many contracts, wages, and benefits (like Social Security) are indexed to inflation. If CPI is understated, these adjustments may not keep up with the actual cost of living, hurting consumers’ purchasing power. A biased CPI affects those in poverty at a far greater level than those who can live comfortably. Many social safety net programs, like food assistance and housing benefits, are adjusted based on CPI. If CPI is biased, these adjustments may not reflect the true increase in living costs, leaving vulnerable populations with insufficient support. If the actual inflation rate is higher than reported, individuals in poverty may struggle more to afford basic necessities like food, housing, and healthcare, exacerbating their financial strain. Many low-wage workers rely on inflation measures to negotiate wage increases. An understated CPI might lead employers to offer smaller raises, further entrenching and widening the income inequality gap. When inflation is understated, policymakers may not recognize the urgency of addressing economic disparities. This can result in fewer resources allocated to programs aimed at alleviating poverty. Rising costs that aren’t accurately reflected in the CPI can lead to heightened stress for those living in poverty, as they struggle to make ends meet while their incomes remain stagnant. An understated CPI value can ultimately make it difficult for those in poverty to escape their cycle of hardship. Minimizing the disparity in the CPI will align with the values of Virtue Ethics, or the branch of philosophy concerned with the importance of developing good moral character and cultivating positive virtues like honesty, courage, and compassion, rather than focusing solely on following rules or maximizing consequences in a given situation.

There are a few main objections to the claims regarding the ethical considerations of the minimization of the CPI. One is the idea of “focusing on what is important”, and the practicality of trying to fix the CPI, which seems to be an inherently behemoth task. However, critiques of the CPI should focus on improving it rather than dismissing it outright. Advocating for better data collection and more representative baskets of goods could enhance its accuracy without undermining its current utility. Critics also argue that in an increasingly complex economy, the idea of a single measure (like the CPI) being entirely accurate for everyone is contentious. Supporters of the CPI argue that, despite its limitations, it provides a necessary framework for understanding inflation on a macroeconomic level. The problem with only relying on measures such as the CPI (that could potentially be biased) is that it can oversimplify and obscure the nuanced realities faced by different demographic groups and regions.

## Final Thoughts

The CPI value should not be biased (or have minimal bias)  because it serves as a key indicator of inflation and reflects the cost of living for citizens. A biased CPI can distort economic policy and mislead government decisions,potentially resulting in inadequate adjustments to social benefits, wages, and interest rates. This can disproportionately affect low-income households, as they often spend a larger portion of their income on essentials. An accurate CPI ensures that citizens are fairly represented in economic assessments, allowing for better financial planning and a more equitable distribution of resources, especially to those who are underrepresented in society.

\newpage

## References

Moulton, Brent R. *Bias in the consumer price index: What is the evidence?* Journal of Economic Perspectives, vol. 10, no. 4, 1 Nov. 1996, pp. 159–177, https://doi.org/10.1257/jep.10.4.159. 


Hausman, Jerry. *Sources of bias and solutions to bias in the consumer price index.* Journal of Economic Perspectives, vol. 17, no. 1, 1 Feb. 2003, pp. 23–44, https://doi.org/10.1257/089533003321164930. 


*Consumer Price Index.* U.S. Bureau of Labor Statistics, U.S. Bureau of Labor Statistics, www.bls.gov/cpi/. Accessed 25 Oct. 2024. 


Krueger, Alan, and Aaron Siskind. *Assessing the Bias in the Consumer Price Index from Survey Data*, Mar. 1998, https://doi.org/10.3386/w6450. 

